# Day 013 - Pandas loc Basic Practice

Focus: basic loc selection, filtering, and updating. Each question has its own DataFrame.

# Question 1: Select One Column

# Dataset
```python -->
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})
```

# Task
Using loc, select only the Name column.

In [8]:
import pandas as pd
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})
df

,Name,Department,Salary
0,Ali,Sales,50000
1,Sara,HR,45000
2,John,IT,70000
3,David,Sales,60000


In [11]:
df.loc[:,['Name']]

,Name
0,Ali
1,Sara
2,John
3,David


## Question 2: Select Multiple Columns

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, select Name and Salary.

In [14]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","IT","Sales"],"Salary":[50000,45000,70000,60000]})

df.loc[:,['Name','Salary']]

,Name,Salary
0,Ali,50000
1,Sara,45000
2,John,70000
3,David,60000


## Question 3: Select One Row

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Salary":[50000,45000,70000]},index=[101,102,103])
```

### Task
Using loc, select the employee with index 102.

In [16]:
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Salary":[50000,45000,70000]},index=[101,102,103])
df

,Name,Salary
101,Ali,50000
102,Sara,45000
103,John,70000


## Question 4: Select Multiple Rows

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]},index=[101,102,103,104])
```

### Task
Using loc, select employees with index 101 and 103.

In [23]:
# Write your answer here

df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]},index=[101,102,103,104])
df.loc[['101','103']]

KeyError: "None of [Index(['101', '103'], dtype='str')] are in the [index]"

## Question 5: Filter Rows

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, select only Sales employees.

In [26]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
df.loc[df['Department']=='Sales']

,Name,Department,Salary
0,Ali,Sales,50000
2,John,Sales,70000


## Question 6: Filter by Salary

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, select employees whose salary is greater than 55000.

In [28]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Salary":[50000,45000,70000,60000]})
df.loc[df['Salary']>55000]

,Name,Salary
2,John,70000
3,David,60000


## Question 7: Filter + Columns

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, select only Name and Salary for Sales employees.

In [31]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
df.loc[df['Department']=='Sales',['Name','Salary']]

,Name,Salary
0,Ali,50000
2,John,70000


## Question 8: Update One Value

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Salary":[50000,45000,70000]})
```

### Task
Using loc, change Ali's salary to 55000.

In [36]:
df=pd.DataFrame({"Name":["Ali","Sara","John"],"Salary":[50000,45000,70000]})
df.loc[df['Name']=='Ali',["Salary"]]=55000
df

,Name,Salary
0,Ali,55000
1,Sara,45000
2,John,70000


## Question 9: Update Multiple Rows

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, change the salary of all Sales employees to 75000.

In [43]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
df.loc[df['Department']=='Sales',['Salary']]=75000

,Name,Department,Salary
0,Ali,Sales,75000
1,Sara,HR,45000
2,John,Sales,75000
3,David,IT,60000


## Question 10: Filter + Update

### Dataset
```python
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
```

### Task
Using loc, change Department to Senior Sales for employees whose salary is greater than 60000.

In [45]:
df=pd.DataFrame({"Name":["Ali","Sara","John","David"],"Department":["Sales","HR","Sales","IT"],"Salary":[50000,45000,70000,60000]})
df.loc[(df['Department']=='Sales')&
        (df['Salary']> 60000),['Department']]='Seniour Sales'

In [46]:
df

,Name,Department,Salary
0,Ali,Sales,50000
1,Sara,HR,45000
2,John,Seniour Sales,70000
3,David,IT,60000
